genre_homepage:
    path:     /
    defaults: { _controller: homeBundle:Genre:index }

genre_create_homepage:
    path:     /create
    defaults: { _controller: homeBundle:Genre:createGenre }

genre_edit_homepage:
    path:     /edit/{id}
    defaults: { _controller: homeBundle:Genre:edit }
    methods: [GET, POST]
    requirements:
        id: \d+

genre_delete_homepage:
    path:     /delete/{id}
    defaults: { _controller: homeBundle:Genre:delete }