front_homepage:
    path:     /
    defaults: { _controller: frontBundle:Default:index }

frontByGenre_homepage:
    path:     /{genre}
    defaults: { _controller: frontBundle:Default:indexByGenre }

#frontByDecade_homepage:
 #   path:     /{decade1}{decade2}
  #  defaults: { _controller: frontBundle:Default:indexByDecade }