<?php

namespace homeBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ActeurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActeurRepository extends EntityRepository
{
    public function getActeurOrderByNomBuilder()
    {
        return $this->createQueryBuilder('a')
            ->orderBy('a.nom', 'ASC');
    }

    public function countActeurs()
    {
        $em = $this->getEntityManager();

        $query = $em->createQuery('SELECT count(a) FROM homeBundle:Acteur a');

        return $query->getSingleScalarResult();
    }

    public function last5Acteurs()
    {
        $em = $this->getEntityManager();

        $query = $em->createQuery('SELECT a FROM homeBundle:Acteur a ORDER BY a.creationTimestamp DESC')
            ->setMaxResults(5);

        return $query->getResult();
    }
}
