<?php

namespace homeBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query\Expr;

/**
 * FilmRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FilmRepository extends EntityRepository
{
    public function filmEtGenre()
    {
        $em = $this->getEntityManager();

        $query = $em->createQuery(
    		'SELECT f, g
            FROM homeBundle:Film f
            LEFT JOIN f.genre g'
        );

        return $query->getResult();
    }

    public function getFilmOrderByNomBuilder()
    {
        return $this->createQueryBuilder('m')
            ->orderBy('m.nom', 'ASC');
    }

    public function countFilms()
    {
        $em = $this->getEntityManager();

        $query = $em->createQuery('SELECT count(f) FROM homeBundle:Film f');

        return $query->getSingleScalarResult();
    }


    public function countFilmsByCategory()
    {
        $query = $this->getEntityManager()
            ->createQuery(
                'SELECT g.nom, COUNT(g) AS nb, g.couleur AS col
                 FROM homeBundle:Film f
                 JOIN f.genre g
                 GROUP BY g.nom'
            );

        return $query->getArrayResult();
    }


    public function last5Films()
    {
        $em = $this->getEntityManager();

        $query = $em->createQuery('SELECT f FROM homeBundle:Film f ORDER BY f.creationTimestamp DESC')
                    ->setMaxResults(5);

        return $query->getResult();
    }

    public function allFilmsbyDate()
    {
        $em = $this->getEntityManager();

        if (!isset($_GET['genre']) && !isset($_GET['dateSortie'])){
            $query = $em->createQuery("SELECT f FROM homeBundle:Film f ORDER BY f.creationTimestamp DESC");
        } else{
            $genre = $_GET['genre'];
            $query = $em->createQuery("SELECT f FROM homeBundle:Film f WHERE f.genre = '$genre' ORDER BY f.creationTimestamp DESC");
        }

        /*if (!isset($_GET['dateSortie'])){
            $query = $em->createQuery("SELECT f FROM homeBundle:Film f ORDER BY f.creationTimestamp DESC");
        } else{
            $dateSortie = $_GET['dateSortie'];
            switch ($dateSortie){
                case '1980':
                    $query = $em->createQuery("SELECT f FROM homeBundle:Film f WHERE f.dateSortie BETWEEN 1980-01-01 AND 1989-12-31 ORDER BY f.creationTimestamp DESC");
                    break;
                case '1990':
                    $query = $em->createQuery("SELECT f FROM homeBundle:Film f WHERE f.dateSortie BETWEEN 1990-01-01 AND 1999-12-31 ORDER BY f.creationTimestamp DESC");
                    break;
                case '2000':
                    $query = $em->createQuery("SELECT f FROM homeBundle:Film f WHERE f.dateSortie BETWEEN 2000-01-01 AND 2009-12-31 ORDER BY f.creationTimestamp DESC");
                    break;
            }

        }*/

        return $query->getResult();
    }

}
