<?php

namespace homeBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query\Expr;

/**
 * FilmRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FilmRepository extends EntityRepository
{
    public function filmEtGenre()
    {
        $em = $this->getEntityManager();

        $query = $em->createQuery(
    		'SELECT f, g
            FROM homeBundle:Film f
            LEFT JOIN f.genre g'
        );

        return $query->getResult();
    }

    public function getFilmOrderByNomBuilder()
    {
        return $this->createQueryBuilder('m')
            ->orderBy('m.nom', 'ASC');
    }

    public function countFilms()
    {
        $em = $this->getEntityManager();

        $query = $em->createQuery('SELECT count(f) FROM homeBundle:Film f');

        return $query->getSingleScalarResult();
    }


    public function countFilmsByCategory()
    {
        $query = $this->getEntityManager()
            ->createQuery(
                'SELECT g.nom, COUNT(g) AS nb, g.couleur AS col
                 FROM homeBundle:Film f
                 JOIN f.genre g
                 GROUP BY g.nom'
            );

        return $query->getArrayResult();
    }


    public function last5Films()
    {
        $em = $this->getEntityManager();

        $query = $em->createQuery('SELECT f FROM homeBundle:Film f ORDER BY f.creationTimestamp DESC')
                    ->setMaxResults(5);

        return $query->getResult();
    }

}
