<?php

namespace homeBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * GenreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GenreRepository extends EntityRepository
{
    public function countGenres()
    {
        $em = $this->getEntityManager();

        $query = $em->createQuery('SELECT count(g) FROM homeBundle:Genre g');

        return $query->getSingleScalarResult();
    }

}
