front:
    resource: "@frontBundle/Resources/config/routing.yml"
    prefix:   /

home:
    resource: "@homeBundle/Resources/config/routing.yml"
    prefix:   /{_locale}
    requirements:
      _locale:  fr|en|de|ar|es

#kms_froala_editor:
    #resource: "@KMSFroalaEditorBundle/Resources/config/routing.yml"
    #prefix:   /froalaeditor

app:
    resource: "@AppBundle/Controller/"
    type:     annotation