# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        in_memory:
            memory:
                users:
                    lanydrak: { password: drakpass, roles: 'ROLE_USER' }
                    admin: { password: admin, roles: 'ROLE_ADMIN' }

        backoffice:
            entity:
                class: homeBundle:User

    encoders:
            Symfony\Component\Security\Core\User\User: plaintext
            homeBundle\Entity\User: bcrypt


    ###
        # 2. Define all roles or users for Authorisation
        ###
        # http://symfony.com/doc/current/book/security.html#hierarchical-roles
    role_hierarchy:
        ROLE_SUPERADMIN:    [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
        ROLE_ADMIN:         [ROLE_ADMIN, ROLE_USER]
        ROLE_USER:          [ROLE_USER]

    firewalls:

        login_firewall:
            pattern: ^/admin/login
            anonymous: true

        main:
            pattern: ^/
            anonymous: true
            #http_basic:
              #realm: "Drak Security"
              #provider: backoffice

            # activate different ways to authenticate

            # http_basic: ~
            # http://symfony.com/doc/current/book/security.html#a-configuring-how-your-users-will-authenticate

            form_login:
                #login_path: /admin/login
                login_path: homeBundle_login
                #check_path: /admin/login_check
                check_path: homeBundle_login_check

                default_target_path: home_homepage

                provider: backoffice

            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html

            logout:
                path: homeBundle_logout
                target: home_homepage

            switch_user:
                provider:             ~
                parameter:            _switch_user
                role:                 ROLE_ALLOWED_TO_SWITCH

    access_control:
            #- { path: ^/, role: ROLE_USER }
            #- { path: ^/fr/api/acteur, roles: ROLE_USER_IP, ip: 10.7.109.66 }

